### ISSUE TITLE
Bot-Viewer: Beenden-Button fehlt im develop Branch

### ISSUE THREAD

**Issue by tsandmann** [tsandmann/ct-sim#17]
Durch die Änderungen im Branch develop (gegenüber master) ist der "Bot Beenden" Button im Bot-Viewer (x) verschwunden, so dass sich ein Bot nicht mehr beenden lässt.

Der Bug wurde vermutlich zwischen Commit 2800379a und 7e2d4d90 eingeführt. Wo genau, ist derzeit unklar.

**Comment by tsandmann** [comment]
Ein schneller Test mit `git bisect` ergab, das Problem existiert seit Commit b760bee. Warum ist unklar, der Code inkl. Commit 3116174 funktioniert noch fehlerfrei.

**Comment by Nightwalker-87** [comment]
Ich mach mich mal auf die Suche dazu, kann grade auch keinen Grund erkennen warum das genau da aufgetreten sein soll...

**Comment by Nightwalker-87** [comment]
https://github.com/tsandmann/ct-sim/commit/b760beea073b488d721412b6dcd2b967b8b69c77#diff-ca40ac5c48726a1ed4689ce481061d0eL146

Hier ist der Fehler. Das semi-manuelle Auto-Replace von Wortsilben hat hier unbemerkt im Code zugeschlagen und einen Datei-Verweis kaputt gemacht. Neben den beiden Files an der Fundstelle sind keine weiteren Dateiverweise betroffen.

**Comment by Nightwalker-87** [comment]
Fixed in commit a3ff2542a00f094d2fe437d53892876763f1c213 and tested successfully.

**Comment by tsandmann** [comment]
ah, sehr gut :)
