### ISSUE TITLE
Veralteter Kommentar in Init.java [33:1]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#18]
> Ubuntu 6.10 + Gnome: Stelle fest, dass c't-Sim absolut bekackt aussieht mit dem Look+Feel des Systems, daher lieber gleich Metal nehmen

Dieser Kommentar müsste mal den aktuellen Gegebenheiten angepasst werden. Die Frage die sich stellt ist, ob das noch zutrifft...

**Comment by Nightwalker-87** [comment]
siehe auch #43

**Comment by tsandmann** [comment]
Trifft immer noch zu, außerdem sind LCD-Anzeige und RemoteCall-Viewer nur für dieses Design ausgelegt.
