### ISSUE TITLE
Dead Link in ClosableTabsPane.java [53:27]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#22]
>  Grundprinzip aus einem <a href="http://forum.java.sun.com/thread.jspa?threadID=337070">Forumsposting von einem Mr_Silly</a> übernommen; Code neu geschrieben und erweitert.

Dead-Link, inzischen ist dadurch unklar worum es sich genau handelt...

**Comment by tsandmann** [comment]
IMHO egal, weil das wurde ja bereits gelöst.

**Comment by Nightwalker-87** [comment]
Neuen Link nach https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6632934 gesetzt, wo das Thema aufgegriffen wird.
