### ISSUE TITLE
Veraltete Information in ClosableTabsPane.java -> Optimierungspotential? [36:11] & [58:11]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#23]
> Diese Klasse ist ein Hack, um auch mit Java 5+ klickbare Icons an der Stelle machen zu können. (Java 6 würde das direkt unterstützen, womit diese Klasse überflüssig wäre. Näheres: <a href="http://java.sun.com/docs/books/tutorial/uiswing/components/tabbedpane.html">Sun's How to Use Tabbed Panes</a>, Abschnitt "Tabs With Custom Components".)

> <em>Theoretisch</em> kann man in einer Instanz dieser Klasse schließbare und nicht-schließbare Tabs gemischt verwenden, aber das habe ich nie getestet. Es ist ein Hack wie gesagt.

Zu prüfen wäre ob hieraus eine Vereinfachung im Code resultieren kann.

**Comment by tsandmann** [comment]
Eigentlich egal, weil die Implementierung ist ja vorhanden und funktioniert.

**Comment by tsandmann** [comment]
Die referenzierte Framework-Klasse würde keine nennenswerte Vereinfachung ergeben.
