### ISSUE TITLE
Ersatz für ct-sim WiPort-Applet (javax.swing.JApplet deprecated since java 9)

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#30]
Angesichts des Deprecated-Status seit Java 9 wird das Packet _javax.swing.JApplet_ mittelfristig wohl aus dem JDK rausfliegen. Darüber hinaus ist der WiPort selbst hardwaremäßig nicht mehr State-of-the-Art und dürfte durch die RaspberryPi-Integration beerbt werden. Hier bietet es sich an eine neue Webserver-basierte Lösung zu entwickeln, welche die Funktionalität des alten WiPort-Applets nachbildet aber idealerweise nicht Java- sondern HTML5 basiert ist, was die zukunfsfähigere Lösung in diesem Bereich darstellt.

Dieses Ticket deckt die folgenden Warnings ab, die seit Java 9 neu hinzugekommen sind:
* line 34, 53: The type JApplet is deprecated since version 9 
* line 90: The method getContentPane() from the type JApplet is deprecated
* line 107, 152, 168: The method getParameter(String) from the type Applet is deprecated
* line 156: The method getCodeBase() from the type Applet is deprecated

**Comment by tsandmann** [comment]
Für ct-Sim sollte Java 8 verwendet werden (aufgrund anderer Probleme bei neueren Java Versionen).
