### ISSUE TITLE
Warning: Resource leak: 'srvSocket' is never closed in TcpConnection.java [109:32]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#31]
Ein möglicher Lösungsansatz für dieses Issue könnte sich an folgendem Problem orientieren:
[resource-leak-in-is-never-closed](https://stackoverflow.com/questions/12519335/resource-leak-in-is-never-closed)

**Comment by tsandmann** [comment]
Lässt sich so nicht lösen, stellt aber auch kein Problem dar, weil `startListening()` nur bei der Initialisierung von `DefaultController` aufgerufen wird und dies nur einmal passiert (in `Main.setupViewAndController()`).
