### ISSUE TITLE
Kommentar zu Variable startTime in Judge.java [45:5]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#36]
> //$$ startTime wofür?

Ist dies ein Hinweis auf fehlende Dokumentation oder eine inhaltliche Frage?

**Comment by tsandmann** [comment]
Ich denke eine inhaltliche Frage, die leicht zu beantworten ist:
https://github.com/tsandmann/ct-sim/blob/618843ff04c331ef4dc8293f795a16cf75e9f25e/ctSim/model/rules/Judge.java#L45

`startTime` ist die Welt-Zeit zu Beginn des Wettkampfes in ms. Wird benötigt in `isAddingBotsAllowed()` und `getTime()`.

**Comment by Nightwalker-87** [comment]
Hmja, die Frage ist wohl wie das gemeint ist... Könnte auch interpretiert werden als "Wofür wird das hier benötigt?". Wenn das eindeutig ist, dann kann das auch weg, eigentlich... startTime ist ja woanders definiert und dort wohl auch beschrieben.

**Comment by tsandmann** [comment]
S.o. wofür das benötigt wird, IMHO ist das eindeutig. Definition und Doku ist genau eine Zeile drunter.

**Comment by Nightwalker-87** [comment]
ah ok, das was du kommentiert hast, hatte ich als zusammenhängend interpretiert als Teil der Variablen-Definition...

**Comment by Nightwalker-87** [comment]
> //$$ startTime wofür? 

Kommentar gelöscht.
