### ISSUE TITLE
Unklare Kommentierungen in BotComponent.java [118:37] & [123:41]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#37]
> // $$$ abstract class

Was ist hiermit gemeint? Soll das ein einfacher Hinweis in Form einer Notiz sein oder aber ein Verweis auf Dokumentation oder ein Verweis auf ein TODO?

**Comment by tsandmann** [comment]
Ein Hinweis, dass die Klasse eine abstrakte Klasse ist. Steht aber eigentlich im Code direkt daneben (`interface`).

**Comment by Nightwalker-87** [comment]
Ok, dann kann aber $$$ eigentlich weg und das wäre ein regulärer Kommentar.

**Comment by Nightwalker-87** [comment]
Fixed.
