### ISSUE TITLE
Hinweis "XML anpassen" in Config.java [394:69]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#38]
Was ist hiermit gemeint? Ist das noch aktuell?

**Comment by tsandmann** [comment]
Gemeint ist vermutlich: Wenn in der config.xml das alte Namensschema nicht mehr verwendet wird, braucht man den Fallback Fall nicht mehr. Schadet aber auch nicht.

**Comment by Nightwalker-87** [comment]
k, entscheidet sich dann ggf. zu einem späteren Zeitpunkt, kann man sich ja nochmal genauer ansehen...
