### ISSUE TITLE
Unklarer Kommentar in ctSim/applet/Main.java [137:81]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#40]
> // $$ images-unterverz

Handelt es sich hier um ein TODO oder um einen regulären Kommentar?

**Comment by tsandmann** [comment]
https://github.com/tsandmann/ct-sim/blob/618843ff04c331ef4dc8293f795a16cf75e9f25e/ctSim/applet/Main.java#L138
Gemeint ist wohl: "Man könnte ein Unterverzeichnis für die Icons anlegen." Das wird durch den Kommentar in der Zeile darüber klar:
https://github.com/tsandmann/ct-sim/blob/618843ff04c331ef4dc8293f795a16cf75e9f25e/ctSim/applet/Main.java#L137

**Comment by Nightwalker-87** [comment]
jo, dann ist das ein potentielles TODO...
