### ISSUE TITLE
Methode finalize() deprecated seit Java 9, betrifft Debug.java [141:19]

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#42]
vielleicht ist ein neuer Ansatz über den GarbageCollector möglich...
Zu berücksichtigen ist hierbei auch der zugehörige Javadoc-Link: @see java.lang.Object#finalize() in [132:6]

**Comment by tsandmann** [comment]
Für ct-Sim sollte Java 8 verwendet werden (aufgrund anderer Probleme bei neueren Java Versionen).
