### ISSUE TITLE
j3d-warnings beim Start des ct-Sim

### ISSUE THREAD

**Issue by Nightwalker-87** [tsandmann/ct-sim#45]
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javax.media.j3d.JoglPipeline (file:/home/nightwalker-87/git/ct-sim/contrib/j3d/j3dcore.jar) to method sun.awt.AppContext.getAppContext()
WARNING: Please consider reporting this to the maintainers of javax.media.j3d.JoglPipeline
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
libEGL warning: DRI2: failed to authenticate
[15 Apr. 2018 1:08:13.249] INFO: Warte auf Verbindung vom c't-Bot auf TCP-Port 10001

Treten diese Erscheinungen auch auf anderen Systemen auf und wenn ja in welcher Form?
Auch hier bietet es sich ggf. an mal einen Blick auf die (möglichen) Ursachen zu werfen.

**Comment by tsandmann** [comment]
Ja

**Comment by tsandmann** [comment]
~~Zur Info: der ct-Sim und die verwendete Java3D-Version funktionieren auch unter Java 12 noch.~~

**Comment by Nightwalker-87** [comment]
Gut zu wissen. Wichtiger ist allerdings dass der c't-Sim unter Java 11 stabil läuft, da das eine LTS-Version ist (was ich schon seit einiger Zeit verwende). Java 12 ist ja nach 6 Monaten schon wieder Geschichte... Aber testen sollte man das natürlich trotzdem regelmäßig mit neueren Versionen.

**Comment by tsandmann** [comment]
Update: Neuere Versionen als Java 8 (1.8.x) funktionieren nicht zuverlässig.
