### ISSUE TITLE
Errors im Branch bugfixes/format_spelling mit Java 10

### ISSUE THREAD

**Issue by tsandmann** [tsandmann/ct-sim#60]
Durch die Änderungen im Branch bugfixes/format_spelling gibt es bei Verwendungen von Java 10 Fehler, die in develop noch nicht auftraten:
- in ParcoursLoader.java: 
  - The type com.sun.j3d.utils.geometry.NormalGenerator is not accessible
  - The method addObstacle(Node, float, float) in the type Parcours is not applicable for the arguments (Box, float, float)
  - The method addFloor(Node, float, float, float) in the type Parcours is not applicable for the arguments (Box, float, float, float)
  - The method addFloor(Node, float, float, float) in the type Parcours is not applicable for the arguments (Box, float, float, float)
  - The method addFloor(Node, float, float, float) in the type Parcours is not applicable for the arguments (Box, float, float, float)
  - NormalGenerator cannot be resolved to a type
  - The method addChild(Node) in the type Group is not applicable for the arguments (Cylinder)
  - The method addLight(Node, float, float, float) in the type Parcours is not applicable for the arguments (Sphere, float, float, float)
  - The method addBPSLight(Node, float, float, float) in the type Parcours is not applicable for the arguments (Sphere, float, float, float) 
  - The type java.awt.image.BufferedImage cannot be resolved. It is indirectly referenced from required .class files
- in ThreeDBot.java:
  - The method addChild(Node) in the type Group is not applicable for the arguments (Sphere)
  - The method addChild(Node) in the type Group is not applicable for the arguments (Box)
- in CtBotShape.java: The import com.sun.j3d.utils.geometry.NormalGenerator cannot be resolved
- in SceneGraphStreamWriterFixed.java: 
  - The import com.sun.j3d.utils.scenegraph.io.NamedObjectException cannot be resolved
  - NamedObjectException cannot be resolved to a type
  - The method writeBranchGraph(BranchGroup, HashMap) from the type SceneGraphStreamWriter refers to the missing type NamedObjectException
- in WorldViewer.java:
  - The type Viewer is not visible
  - The type ViewingPlatform is not visible

Wenn man das Projekt mit Java 8 baut, treten die Fehler nicht auf. Da die Fehler in develop aber auch mit Java 10 nicht auftreten, ist in bugfixes/format_spelling wohl irgendetwas kaputt gegangen. 
Vielleicht stimmt dort etwas mit den Projekteinstellungen nicht, so dass die Imports nicht richtig gefunden werden?

**Comment by Nightwalker-87** [comment]
Update: Fehler wird durch verdeckten Konflikt zwischen j3d.utils (import com.sun.j3d.utils.geometry.NormalGenerator;) und jSerialComm 2.0.2 ausgelöst, von dem der Compiler nix mitbekommt und sich folglich auch nicht beschwert. Da das Problem darüber hinaus unter Java 8 nicht existiert und nur unter Java 10, ist der Fehler lange unentdeckt "verschleppt" worden.

**Comment by Nightwalker-87** [comment]
Weitere Tests ergaben: jSerialComm 1.3.11 ist die neueste Version die keinen Konflikt generiert unter Java 10. Neuere Versionen 2.0.0/2.0.1/2.0.2 lassen die Inkompatibität wieder aufleben. Fehlerursache ist vermutlich im jSerialComm Projekt zu suchen...

**Comment by Nightwalker-87** [comment]
Fixed with commit 3f7281c52105a2cf830640cc237476f0b9b26327.

**Comment by tsandmann** [comment]
fixed with 5e1d26290878a90af5334f94c3d030b1d024514d
