### ISSUE TITLE
Wrong map start position if only "0" field is defined

### ISSUE THREAD

**Issue by r4dh4l** [tsandmann/ct-sim#62]
If there is only a map field `0` the Bot should start on this field according to https://github.com/tsandmann/ct-sim/blob/4779931b9811de13da2dbc3e3be06527aee74dc7/ctSim/model/Parcours.java#L477 but currently the Bot is placed into an `*` field (light source) instead.

Edit: `0` is currently the start position for a 3. Bot called to a map (and any additional Bot).

**Comment by tsandmann** [comment]
> but currently the Bot is placed into an `*` field (light source) instead.

the new bot is not necessarily placed on a `*` field, it's placed on the field at the bottom left corner of the course.

**Comment by r4dh4l** [comment]
Ok, I see. The bug fix https://github.com/tsandmann/ct-sim/commit/df2e8c5d6a056f7f52784161b2f1c8182592d46c works, the bot is now starting on a `0` field if no startposition `1` is provided.

Now the description in https://github.com/tsandmann/ct-sim/blob/f1374e7e1f4d1a96ee6e2d8d5d81e52421d6048c/parcours/template.xml#L36 should be changed to

```
O | Bodenplatte Startpunkt Default; hier startet jeder aufgerufene Bot, sofern keine "Bodenplatte Startpunkt Bot1" auf der Karte vorhanden ist (30)
```

Do you need a patch file for this @tsandmann ?

**Comment by tsandmann** [comment]
> ...
> should be changed to
> ```
> O | Bodenplatte Startpunkt Default; hier startet jeder aufgerufene Bot, sofern keine "Bodenplatte Startpunkt Bot1" auf der Karte vorhanden ist (30)
> ```
> Do you need a patch file for this @tsandmann ?

done.
