### ISSUE TITLE
Parcours "adventcal.xml" nicht geschlossen

### ISSUE THREAD

**Issue by tsandmann** [tsandmann/ct-sim#63]
@r4dh4l: Da der Parcours [adventcal.xml](../blob/master/parcours/adventcal.xml) nicht vollständig geschlossen ist, können Bots unten "herausfahren" und stecken dann fest.

**Comment by r4dh4l** [comment]
@tsandmann Danke für den Hinweis, hab das nicht vergessen und "repariere" das (irgendwann, aber ganz sicher).

**Comment by tsandmann** [comment]
Habe den Parcours mal (leicht) angepasst, um das Ticket schließen zu können.
@r4dh4l: Wenn du eine andere Variante für besser hältst, gerne aktualisieren!

**Comment by r4dh4l** [comment]
@tsandmann Alles bestens, Danke Dir und entschuldige, dass ich das nicht selbst gemacht habe. Ich behalte meine Mail im Postfach als Reminder, um irgendwann nochmal über die Beschreibung der virtuellen Bauelemente zu gehen. Die wirken hier und da "übermüdet" geschrieben.
